
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BeautySalon
{

using System;
    using System.Collections.Generic;
    
public partial class Employee
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Employee()
    {

        this.Master = new HashSet<Master>();

    }


    public int EmployeeID { get; set; }

    public bool IsWorking { get; set; }

    public int IDRole { get; set; }

    public System.DateTime BirthDate { get; set; }

    public string Login { get; set; }

    public string Password { get; set; }

    public int IDPerson { get; set; }



    public virtual Person Person { get; set; }

    public virtual Role Role { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Master> Master { get; set; }

}

}
