

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BeautySalon
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class BeautySalonDBEntities : DbContext
{
    public BeautySalonDBEntities()
        : base("name=BeautySalonDBEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Client> Client { get; set; }

    public virtual DbSet<Discount> Discount { get; set; }

    public virtual DbSet<Employee> Employee { get; set; }

    public virtual DbSet<Master> Master { get; set; }

    public virtual DbSet<Person> Person { get; set; }

    public virtual DbSet<Position> Position { get; set; }

    public virtual DbSet<Procedure> Procedure { get; set; }

    public virtual DbSet<ProcedureInRecording> ProcedureInRecording { get; set; }

    public virtual DbSet<ProcedureOfMaster> ProcedureOfMaster { get; set; }

    public virtual DbSet<Recording> Recording { get; set; }

    public virtual DbSet<Role> Role { get; set; }

}

}

