
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BeautySalon
{

using System;
    using System.Collections.Generic;
    
public partial class ProcedureOfMaster
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ProcedureOfMaster()
    {

        this.ProcedureInRecording = new HashSet<ProcedureInRecording>();

    }


    public int ProcedureOfMasterID { get; set; }

    public int IDMaster { get; set; }

    public int IDProcedure { get; set; }



    public virtual Master Master { get; set; }

    public virtual Procedure Procedure { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ProcedureInRecording> ProcedureInRecording { get; set; }

}

}
