
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BeautySalon
{

using System;
    using System.Collections.Generic;
    
public partial class ProcedureInRecording
{

    public int ProcedureInRecordingID { get; set; }

    public int IDProcedureOfMaster { get; set; }

    public int IDRecording { get; set; }

    public System.TimeSpan Time { get; set; }

    public bool IsCanceled { get; set; }

    public bool IsVisited { get; set; }



    public virtual ProcedureOfMaster ProcedureOfMaster { get; set; }

    public virtual Recording Recording { get; set; }

}

}
